version: '3.8'

services:
  database:
    container_name: DB
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: CarDB

  api:
    container_name: API
    build: api
    ports:
        - 8000:8000
    depends_on:
        - database